---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Ensure iptables is installed (different per OS)
      ansible.builtin.package:
        name: "{{ iptables_pkg }}"
        state: present
      vars:
        iptables_pkg: >-
          {% if ansible_os_family == 'Debian' %}
          iptables
          {% elif ansible_os_family == 'RedHat' %}
          iptables-nft
          {% elif ansible_os_family == 'Suse' %}
          iptables
          {% else %}
          iptables
          {% endif %}

    - name: Wait for systemd to be ready
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: mzwoelfer.ansible_nerdctl
      vars:
        nerdctl_rootless: false
