---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Create test user '{{ nerdctl_user }}'
      ansible.builtin.user:
        name: "{{ nerdctl_user }}"
        shell: /bin/bash
        create_home: true

    - name: Add 'user' to sudoers (NOPASSWD)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ nerdctl_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Check if lingering is already enabled
      ansible.builtin.stat:
        path: "/var/lib/systemd/linger/{{ nerdctl_user }}"
      register: linger_file

    - name: Enable lingering for '{{ nerdctl_user }}'
      command: "loginctl enable-linger {{ nerdctl_user }}"
      when: not linger_file.stat.exists

    - name: Create /run/user/1000 directory
      ansible.builtin.file:
        path: "/run/{{ nerdctl_user }}/1000"
        state: directory
        owner: "{{ nerdctl_user }}"
        group: "{{ nerdctl_user }}"
        mode: '0700'

    - name: Set XDG_RUNTIME_DIR for Molecule
      set_fact:
        xdg_runtime_dir: "/run/{{ nerdctl_user }}/1000"

    - name: Check if DBUS session is already in .bashrc
      become_user: "{{ nerdctl_user }}"
      ansible.builtin.shell: grep -q "DBUS_SESSION_BUS_ADDRESS" ~/.bashrc
      register: dbus_bashrc_check
      failed_when: false
      changed_when: false

    - name: Bootstrap dbus session and store env
      become_user: "{{ nerdctl_user }}"
      shell: |
        eval $(dbus-launch --sh-syntax)
        echo "export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" >> ~/.bashrc
        echo "export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" > ~/.dbus_env
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
      when: dbus_bashrc_check.rc != 0

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to be ready
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: mzwoelfer.ansible_nerdctl
      vars:
        nerdctl_rootless: false
