---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver: 
  name: docker

platforms:
  - name: "Rootful nerdctl ${MOLECULE_DISTRO:-debian12}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: "/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
