- name: Run containerd rootless setup as non-root user
  ansible.builtin.command:
    cmd: containerd-rootless-setuptool.sh install
  become_user: "{{ nerdctl_user }}"
  when: nerdctl_rootless_install

- name: Enable and start containerd for rootful nerdctl
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started
  when: not nerdctl_rootless_install
