- name: Run containerd rootless setup as non-root user
  ansible.builtin.command:
    cmd: containerd-rootless-setuptool.sh install
  become_user: "{{ ansible_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
