- name: Ensure iptables and ip6tables accessible in $PATH
  become: true
  block:
    - name: Check if iptables and ip6tables are installed
      ansible.builtin.stat:
        path: "/usr/sbin/{{ item }}"
      loop:
        - iptables
        - ip6tables
      register: iptables_check

    - name: Create symlink for iptables and ip6tables for path in $PATH
      file:
        src: "/usr/sbin/{{ item.item }}"
        dest: "/usr/local/bin/{{ item.item }}"
        state: link
      loop: "{{ iptables_check.results }}"
      when: item.stat.exists
