---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Create test user 'user'
      ansible.builtin.user:
        name: user
        shell: /bin/bash
        create_home: true
      become: true

    - name: Add 'user' to sudoers (NOPASSWD)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "user ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
      become: true

    - name: Enable lingering for 'user'
      command: loginctl enable-linger user
      become: true

    - name: Create /run/user/1000 directory
      ansible.builtin.file:
        path: /run/user/1000
        state: directory
        owner: user
        group: user
        mode: '0700'
      become: true

    - name: Set XDG_RUNTIME_DIR for Molecule
      set_fact:
        xdg_runtime_dir: "/run/user/1000"

    - name: Bootstrap dbus session and store env
      become_user: user
      shell: |
        eval $(dbus-launch --sh-syntax)
        echo "export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" >> ~/.bashrc
        echo "export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" > ~/.dbus_env
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to be ready
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        nerdctl_rootless_install: false
      ansible_user: user
