---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver: 
  name: docker

platforms:
  - name: debian12
    image: trfore/docker-debian12-systemd
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
