---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver: 
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    user: user
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          ansible_user: user
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
