---
- name: Rootless Testing of ansible-nerdctl
  hosts: all

  vars:
    nerdctl_user: user1
    nerdctl_user_uid: 1000  # default UID for first non-root user

  pre_tasks:
    - name: Create test user '{{ nerdctl_user }}'
      ansible.builtin.user:
        name: "{{ nerdctl_user }}"
        shell: /bin/bash
        create_home: true
      become: true

    - name: Add '{{ nerdctl_user }}' to sudoers (NOPASSWD)
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ nerdctl_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
      become: true

    - name: Enable lingering for '{{ nerdctl_user }}' (so user services can run)
      ansible.builtin.command: "loginctl enable-linger {{ nerdctl_user }}"
      become: true
      changed_when: false
      failed_when: false  # in CI containers loginctl often fails harmlessly

    - name: Prepare fake XDG_RUNTIME_DIR for rootless user
      ansible.builtin.file:
        path: "/run/user/{{ nerdctl_user_uid }}"
        state: directory
        owner: "{{ nerdctl_user }}"
        group: "{{ nerdctl_user }}"
        mode: '0700'
      become: true

    - name: Export XDG_RUNTIME_DIR fact
      set_fact:
        xdg_runtime_dir: "/run/user/{{ nerdctl_user_uid }}"

    - name: Bootstrap minimal dbus + systemd user session
      become_user: "{{ nerdctl_user }}"
      ansible.builtin.shell: |
        export XDG_RUNTIME_DIR="{{ xdg_runtime_dir }}"
        mkdir -p "$XDG_RUNTIME_DIR"
        eval "$(dbus-launch --sh-syntax)"
        echo "export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" > ~/.dbus_env
        echo "export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}" >> ~/.dbus_env
        grep -q DBUS_SESSION_BUS_ADDRESS ~/.bashrc || echo "export DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}" >> ~/.bashrc
        grep -q XDG_RUNTIME_DIR ~/.bashrc || echo "export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}" >> ~/.bashrc
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
      changed_when: false

    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      become: true

    - name: Wait for systemd (if available)
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: "'running' in systemctl_status.stdout or 'degraded' in systemctl_status.stdout"
      retries: 10
      delay: 3
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: false  # skip failure if container doesn’t use full systemd

  roles:
    - role: mzwoelfer.ansible_nerdctl

