---
- name: Converge
  hosts: all

  pre_tasks:
    - name: apt update (on Debian)
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Ensure iptables is installed (different per OS)
      become: true
      ansible.builtin.package:
        name: "{{ iptables_pkg }}"
        state: present
      vars:
        iptables_pkg: >-
          {% if ansible_os_family == 'Debian' %}
          iptables
          {% elif ansible_os_family == 'RedHat' %}
          iptables-nft
          {% elif ansible_os_family == 'Suse' %}
          iptables
          {% else %}
          iptables
          {% endif %}

    - name: Create non-root test user for rootless install
      become: true
      ansible.builtin.user:
        name: testuser
        shell: /bin/bash
        create_home: true

    - name: Wait for systemd to be ready
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    # ---- rootless user-session bootstrap for Docker Molecule ----

    - name: Get testuser UID
      ansible.builtin.command: "id -u testuser"
      register: testuser_uid_cmd
      changed_when: false

    - name: Set testuser UID fact
      ansible.builtin.set_fact:
        testuser_uid: "{{ testuser_uid_cmd.stdout }}"

    - name: Ensure /run/user/UID exists
      become: true
      ansible.builtin.file:
        path: "/run/user/{{ testuser_uid }}"
        state: directory
        owner: testuser
        group: testuser
        mode: "0700"

    - name: Start per-user systemd manager (user@UID.service)
      become: true
      ansible.builtin.systemd_service:
        name: "user@{{ testuser_uid }}.service"
        state: started

  tasks:
    - name: Apply nerdctl role (rootless) with user bus env
      ansible.builtin.include_role:
        name: mzwoelfer.ansible_nerdctl
      vars:
        nerdctl_rootless: true
        nerdctl_user: testuser
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ testuser_uid }}"
        DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ testuser_uid }}/bus"

