---
role_name_check: 1

dependency:
  name: galaxy
  options:
    ignore-errors: true

driver: 
  name: docker

platforms:
  - name: instance
    image: ghcr.io/molecule-systemd/docker-systemd:debian12
    command: "/sbin/init"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    environment:
      container: docker

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
